# Generated by Django 4.2.6 on 2023-10-29 09:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pelatihan', '0002_remove_bank_kode_remove_kecamatan_kode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis_pelatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=221)),
            ],
            options={
                'db_table': 'jenis_pelatihan',
            },
        ),
        migrations.AddField(
            model_name='pelatihan',
            name='jenis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pelatihan.jenis_pelatihan'),
            preserve_default=False,
        ),
    ]
